# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WiproExercise' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'SVProgressHUD'
	pod 'SDWebImage', '~> 4.0'
  # Pods for WiproExercise

  target 'WiproExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WiproExerciseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
